language: php
php:
  - '7.0'
  - '7.1'
  - hhvm
  - hhvm-nightly
  - nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: nightly
        - php: hhvm-nightly

# Todo: Add PhpUnit tests for this tiny service

script:
  - make build
  - make migrate
  - make test
